### ISSUE TITLE
【login】已登录的用户，点击面包屑的Home，跳出了登录

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#21]
1、用户已登录系统，在系统中任意页面，点击面包屑中的Home
期望：显示home页面
实际：跳出了登录
![image](https://user-images.githubusercontent.com/58163131/94386580-9c9b6680-017a-11eb-8864-8182996b8094.png)

**Comment by xiaoxiaoting** [comment]
系统去掉导航栏
