### ISSUE TITLE
【Namespace】期望可以控制下key，value的字符长度

### ISSUE THREAD

**Issue by lydiaye** [bob-sponge/kvhub#23]
1.新增页面需要控制字符长度
2.查看页面如果字符过长，需要优化页面显示

![字符超长](https://user-images.githubusercontent.com/62370186/94394343-b1362980-018f-11eb-8ba9-de6251b1b05c.png)

**Comment by xiaoxiaoting** [comment]
keyname 以及翻译， 字符长度最大限制500.
