### ISSUE TITLE
【Create Request】create request 创建成功以后页面空白

### ISSUE THREAD

**Issue by lydiaye** [bob-sponge/kvhub#29]
http://10.192.30.203/branch/26
【步骤】
1.进入该链接
2.选择dev->master 进行compare，然后点create request
3.页面空白

![image](https://user-images.githubusercontent.com/62370186/94397200-e5ace400-0195-11eb-8784-09ad9d72f3ed.png)

![WechatIMG954](https://user-images.githubusercontent.com/26305905/94516358-3a189800-0258-11eb-94ec-f8d2a8f14c2a.jpeg)

**Comment by wanglovedu** [comment]
![Uploading image.png…]()

**Comment by xiaoxiaoting** [comment]
source 和 target返回的数据有问题

**Comment by lydiaye** [comment]
验证通过
