### ISSUE TITLE
【Merge】点了merge按钮以后页面空白，并且查询列表上的操作按钮仍然存在

### ISSUE THREAD

**Issue by lydiaye** [bob-sponge/kvhub#30]
http://10.192.30.203/mergeRequest/22

![image](https://user-images.githubusercontent.com/62370186/94397701-f3af3480-0196-11eb-8c76-c923d5a15144.png)

![image](https://user-images.githubusercontent.com/62370186/94397905-21947900-0197-11eb-80ae-85eca1f757b1.png)

**Comment by wanglovedu** [comment]
#29 问题的后续，进入页面没有数据是因为前端存在问题，当进入页面选择好分支后，点击提交按钮之后才会对merge request进行锁定。那时外面的merge才会隐藏

**Comment by LiGeng888** [comment]
验证通过，请关闭。

**Comment by lydiaye** [comment]
ok
