### ISSUE TITLE
【namespace】language列表页面，选择了指定分支，选择namespace进入页面，建议与列表页面所选分支一致

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#31]
1、language列表页面，选择分支b1
2、选择任意namespace，进入详情
期望：显示b1分支
实际：还是选择的master，需要手动切换

**Comment by zhoujie0732** [comment]
![1](https://user-images.githubusercontent.com/58163131/94398575-666cdf80-0198-11eb-9ec9-273fbc5f31a4.png)
![2](https://user-images.githubusercontent.com/58163131/94398586-6967d000-0198-11eb-8dd7-0b9fa534ac4f.png)

**Comment by zhoujie0732** [comment]
![1](https://user-images.githubusercontent.com/58163131/94398679-95835100-0198-11eb-9dbf-7b9225add415.png)
![2](https://user-images.githubusercontent.com/58163131/94398683-96b47e00-0198-11eb-8b1a-663b61397c50.png)

**Comment by xiaoxiaoting** [comment]
不需要记住分支
