### ISSUE TITLE
【merge request】项目中两个分支，merge结束后，删除1个分支，merge request列表中，title缺失（这种情况能删吗？）；且后续再建并提交，其他merge都失败

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#32]
http://10.192.30.203/mergeRequest/18
![1](https://user-images.githubusercontent.com/58163131/94399938-dda37300-019a-11eb-9dc5-4a6c3c27abf8.png)
![2](https://user-images.githubusercontent.com/58163131/94401129-b0f05b00-019c-11eb-804c-d2c8259ef708.png)

**Comment by Imoke** [comment]
可以删除，列表中title不为空

**Comment by zhoujie0732** [comment]
已验证
