### ISSUE TITLE
【namespace】查询key，组合字段查询不到内容[\=-

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#34]
1、新建key为   `~!@#$%^&*()_+{}|:"<>?/.,';][\=-
2、查询时查不到
输入完整内容查不到，测试输入[\=-组合的问题，单个字符都能查到
![image](https://user-images.githubusercontent.com/58163131/94403281-c61ab900-019f-11eb-9572-43e6d42681e1.png)

**Comment by xiaoxiaoting** [comment]
能搜到，后端问题。

**Comment by zhoujie0732** [comment]
已验证
