### ISSUE TITLE
[language]删除语言时，二次确认提示，需要更明确告知，删除语言，则各个分支中的key里，对应语言的内容都会删除

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#41]
![image](https://user-images.githubusercontent.com/58163131/94521545-d777ca00-0260-11eb-8b71-6720e4d061c2.png)

**Comment by Imoke** [comment]
Are you sure to delete this language？ 这样翻译就行

**Comment by zhoujie0732** [comment]
已验证
