### ISSUE TITLE
[merge request]创建merge request 报500

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#49]
1、新建工程默认语言中文
2、添加英文
3、新建namespace，master分支创建keyA
4、新建dev分支，并在dev分支创建keyB
5、新建merge request，选择dev-》master
期望：正常创建
实际：报500
http://10.192.30.203/branch/compare/145
![image](https://user-images.githubusercontent.com/58163131/95552199-def85980-0a3e-11eb-9c3a-c10c99cea82f.png)

**Comment by LiGeng888** [comment]
测试通过，可以关闭。
