### ISSUE TITLE
【password】管理员在用户管理中重置密码，或者修改自身密码，限制密码长度，否则超过256个字符，报错

### ISSUE THREAD

**Issue by zhoujie0732** [bob-sponge/kvhub#52]
![image](https://user-images.githubusercontent.com/58163131/95554374-aa869c80-0a42-11eb-8c25-57414130c7cd.png)

**Comment by zhoujie0732** [comment]
建议限制20个字符即可，当前正好输入256个字符，还是报错

**Comment by xiaoxiaoting** [comment]
密码包含字母，数字，特殊字符(~!@#$%^&*)且长度在6-16位之间。

**Comment by zhoujie0732** [comment]
已验证
