### ISSUE TITLE
【Namespace】将namespace删除以后，在建一个重名的会报重复，期望可以新增成功

### ISSUE THREAD

**Issue by lydiaye** [bob-sponge/kvhub#59]
步骤：
1.新建namespace：test01
2.将test01删除
3.删除以后再建一个同名 test01
【期望结果】能新建成功
【实际结果】提示namespace名称重复

http://10.192.30.203/languages/59
在该project下新建 test01可以复现

![image](https://user-images.githubusercontent.com/62370186/95650721-ed667400-0b17-11eb-81da-b1a484881550.png)
![image](https://user-images.githubusercontent.com/62370186/95650727-f6efdc00-0b17-11eb-9f19-7112525da23c.png)

**Comment by LiGeng888** [comment]
测试通过，可以关。

**Comment by lydiaye** [comment]
验证通过
