### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by wangtao0101** [bob-sponge/kvhub#8]
名字改成kvhub（[KV]hub和i[18]n类似），图标也换掉
![1586318087192-efe8dbf3-1e43-426f-9354-59b4ff69a134](https://user-images.githubusercontent.com/2182570/78863910-38220900-7a6d-11ea-815a-5e62094f77b1.png)
![1586251824341-0a36ab04-8d41-4e88-8346-aebb081cfb31](https://user-images.githubusercontent.com/2182570/78863951-4b34d900-7a6d-11ea-9146-1742c0a85449.png)
![1586251824333-93fe0bea-8a25-4847-97ca-96f2c0ee2256](https://user-images.githubusercontent.com/2182570/78863954-4cfe9c80-7a6d-11ea-9db6-2569cbcd0258.png)

**Comment by Imoke** [comment]
登录类型去掉，不支持

**Comment by Imoke** [comment]
@wanglovedu  8/25
@xiaoxiaoting 8/31
@lydiaye 9/1
