### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by wangtao0101** [bob-sponge/kvhub#9]
![Inked1586318087189-be98463d-721d-43a1-871a-32566dafca27_LI](https://user-images.githubusercontent.com/2182570/78864457-3dcc1e80-7a6e-11ea-8b1f-e8bde1d96f25.jpg)

**Comment by Imoke** [comment]
1.用户信息：点击用户名按钮，显示用户个人信息，分两个 tab(用户信息 / 修改密码 ) 
   用户信息显示包括（用户名，用户类型，上次登录时间）
2.用户管理只有管理员权限的用户可见
3.用户管理列表包括：用户名，用户类型，上次登录时间 和 操作项
  其中操作项包括： 删除用户，重置密码，设置为管理员
4.对于页面中出现的删除操作（删除工程，namespace, branch ）和 merge request 操作，只有管理员可见

**Comment by Imoke** [comment]
@xiaokexiang 9/1
@sevenbian 9/7
@zhoujie0732 9/14
